### ISSUE TITLE
 Need to load full model in order to do transfer learning.

### ISSUE THREAD

**Issue by arianaa30** [odigous-labs/video-summarization#8]
Nice work. I was trying to simply run `python main.py` with the video path, but got this error:

`video-summarization-develop\src\net\netarch.py", line 104, in _load_yolo_model
    raise ValueError('Need to load full model in order to do '
ValueError: Need to load full model in order to do transfer learning. Run script again with desired TL config and weight file to generate model.`

Is there anything missing?

**Comment by oshadaamila** [comment]
Thank you for the interest in our work, You need to add a pre-trained YOLO model to the source folder in order to make the code run. A compatible model trained on coco dataset can be found [here. ](https://www.dropbox.com/s/dr4qh2xo1ksaj6r/coco.h5?dl=0)

Add it to the source folder and then change the 120th line in the src/net/netparams.py as below
replace  `IN_MODEL = "coco_model.h5"` with  `IN_MODEL = "file name of your model with extension"`

**Comment by arianaa30** [comment]
Thanks for the hint. Now it goes further, but this error. Looks like there is a problem with the way you load models in Keras. Are you sure it works?!

```
Folder Creating Process Started
Process Finished Successfully
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    run()
  File "main.py", line 46, in run
    location_to_store_shot_frames
  File "C:\Users\user\Downloads\video-summarization-develop\src\objects_identifier_of_frames.py", line 20, in generate_object_list_of_frames
    return YOLO().predict(input_frames_path)
  File "C:\Users\user\Downloads\video-summarization-develop\src\yolo\model.py", line 17, in __init__
    self.model = self.yolo_arch.get_model()
  File "C:\Users\user\Downloads\video-summarization-develop\src\net\netarch.py", line 76, in get_model
    yolo_model = self._load_yolo_model()
  File "C:\Users\user\Downloads\video-summarization-develop\src\net\netarch.py", line 100, in _load_yolo_model
    model = load_model(self.in_model_name, compile=False)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.
```
